#!/usr/bin/env python3
"""Generate PDF from SEO_ACTION_PLAN_3_MONTHS.txt"""
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font("Courier", "B", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, "Creative Metal Industries - SEO Action Plan", align="C")
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Courier", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

pdf = PDF(orientation="P", unit="mm", format="A4")
pdf.set_auto_page_break(auto=True, margin=20)
pdf.add_page()
pdf.set_font("Courier", "", 9)

with open("SEO_ACTION_PLAN_3_MONTHS.txt", "r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        # Replace problematic characters
        line = line.replace("\u2713", "[done]")
        line = line.replace("\u2717", "[todo]")
        line = line.replace("\u2022", "*")
        line = line.replace("\u2014", "--")
        line = line.replace("\u2019", "'")
        line = line.replace("\u201c", '"')
        line = line.replace("\u201d", '"')
        line = line.replace("\u2026", "...")
        line = line.replace("\u2500", "-")
        line = line.replace("\u2502", "|")
        line = line.replace("\u250c", "+")
        line = line.replace("\u2510", "+")
        line = line.replace("\u2514", "+")
        line = line.replace("\u2518", "+")
        line = line.replace("\u251c", "+")
        line = line.replace("\u2524", "+")
        line = line.replace("\u252c", "+")
        line = line.replace("\u2534", "+")
        line = line.replace("\u253c", "+")
        line = line.replace("\u2550", "=")
        line = line.replace("\u2551", "|")
        line = line.replace("\u2554", "+")
        line = line.replace("\u2557", "+")
        line = line.replace("\u255a", "+")
        line = line.replace("\u255d", "+")
        # Encode safely
        safe = line.encode("latin-1", errors="replace").decode("latin-1")
        pdf.cell(0, 4, safe, ln=True)
        line = line.replace("\u2014", "--")
        line = line.replace("\u2013", "-")
        line = line.replace("\u2019", "'")
        line = line.replace("\u2018", "'")
        line = line.replace("\u201c", '"')
        line = line.replace("\u201d", '"')
        line = line.replace("\u2026", "...")
        line = line.replace("\u2500", "-")
        line = line.replace("\u2502", "|")
        line = line.replace("\u250c", "+")
        line = line.replace("\u2510", "+")
        line = line.replace("\u2514", "+")
        line = line.replace("\u2518", "+")
        line = line.replace("\u251c", "+")
        line = line.replace("\u2524", "+")
        line = line.replace("\u252c", "+")
        line = line.replace("\u2534", "+")
        line = line.replace("\u253c", "+")
        line = line.replace("\u2550", "=")
        line = line.replace("\u2551", "|")
        line = line.replace("\u2554", "+")
        line = line.replace("\u2557", "+")
        line = line.replace("\u255a", "+")
        line = line.replace("\u255d", "+")
        line = line.replace("\u2501", "-")
        line = line.replace("\u2503", "|")
        line = line.replace("\u2517", "+")
        line = line.replace("\u251b", "+")
        line = line.replace("\u2523", "+")
        line = line.replace("\u252b", "+")
        line = line.replace("\u250f", "+")
        line = line.replace("\u2513", "+")
        line = line.replace("\u203a", ">")
        line = line.replace("\u2713", "[Y]")
        line = line.replace("\u2717", "[N]")
        line = line.replace("\u2022", "*")
        line = line.replace("\u2588", "#")
        line = line.replace("\u2580", "=")
        line = line.replace("\u2584", "=")
        line = line.replace("\u2591", ".")
        line = line.replace("\u2592", "=")
        line = line.replace("\u2593", "#")
        # Remove any remaining non-latin1 chars
        safe = line.encode("latin-1", errors="replace").decode("latin-1")
        pdf.cell(0, 4, safe, ln=True)

pdf.output("SEO_ACTION_PLAN_3_MONTHS.pdf")
print("PDF generated: SEO_ACTION_PLAN_3_MONTHS.pdf")
