import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  ssr: true,
  server: {
    preset: "vercel",
    // Remove trailing slashes to prevent duplicate URL indexing
    prerender: {
      crawlLinks: true,
      routes: [
        "/steel-pipe-supplier-chennai",
        "/steel-pipe-supplier-hyderabad",
        "/steel-pipe-supplier-bangalore",
        "/steel-pipe-supplier-kolkata",
        "/steel-pipe-supplier-delhi",
        "/steel-pipe-supplier-jaipur",
        "/steel-supplier-indore",
        "/steel-pipe-supplier-coimbatore",
        "/steel-pipe-supplier-vizag",
        "/steel-supplier-nagpur",
        "/steel-supplier-bhopal",
        "/steel-pipe-supplier-ludhiana",
        "/steel-supplier-kanpur",
        "/steel-supplier-raipur",
        "/steel-pipe-supplier-kochi",
        "/steel-supplier-haldia",
        "/steel-supplier-jamnagar",
        "/steel-supplier-hazira",
        "/steel-supplier-mundra",
        "/steel-supplier-kandla",
        "/steel-supplier-mangalore",
        "/steel-supplier-vadodara-gidc",
        "/steel-supplier-ankleshwar-gidc",
        "/steel-supplier-vapi-gidc",
        "/steel-supplier-panoli-gidc",
        "/steel-supplier-jhagadia",
        "/steel-pipe-supplier-gandhidham",
        "/steel-supplier-silvassa",
        "/steel-pipe-supplier-thane",
        "/steel-pipe-supplier-navi-mumbai",
        "/steel-supplier-chakan-pune",
        "/steel-supplier-patalganga",
        "/steel-pipe-supplier-aurangabad",
        "/steel-pipe-supplier-bhubaneswar",
        "/steel-supplier-kakinada",
        "/steel-pipe-supplier-trichy",
        "/steel-pipe-supplier-madurai",
        "/steel-supplier-paradip",
        "/steel-supplier-numaligarh",
        "/steel-supplier-mathura",
        "/steel-supplier-panipat",
        "/steel-supplier-koyali",
        "/steel-pipe-supplier-goa",
        "/steel-supplier-chandigarh",
        "/steel-supplier-durgapur",
        "/steel-supplier-rourkela",
        "/steel-supplier-salem",
        "/steel-pipe-supplier-hubli",
        "/steel-pipe-supplier-vasai",
        "/steel-supplier-dahej",
        "/ss-310-pipe-supplier-india",
        "/ss-310s-plate-supplier-india",
        "/ss-321-pipe-supplier-india",
        "/ss-321h-tube-supplier-india",
        "/ss-347-pipe-supplier-india",
        "/ss-347h-tube-supplier-india",
        "/ss-410-pipe-supplier-india",
        "/ss-430-sheet-supplier-india",
        "/ss-904l-pipe-supplier-india",
        "/duplex-2205-plate-supplier-india",
        "/super-duplex-2507-pipe-supplier",
        "/duplex-2205-fittings-supplier-india",
        "/duplex-2205-flanges-supplier-india",
        "/super-duplex-2507-fittings-supplier",
        "/super-duplex-2507-flanges-supplier",
        "/inconel-600-pipe-supplier-india",
        "/inconel-718-supplier-india",
        "/incoloy-825-pipe-supplier-india",
        "/monel-k500-supplier-india",
        "/hastelloy-c22-pipe-supplier-india",
      ],
    },
  },
});
